# Generated by Django 5.0.3 on 2025-06-14 21:12

import WoSModels.models
import WoSModels.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.URLField(default='https://i14.servimg.com/u/f14/17/55/69/45/evergr10.jpg')),
                ('avatar', models.URLField(default='https://avatars.githubusercontent.com/u/57301293?v=4')),
            ],
            options={
                'verbose_name': 'Image Links',
                'verbose_name_plural': 'Image Links',
            },
        ),
        migrations.CreateModel(
            name='NavSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('url', models.CharField(blank=True, help_text='Internal or external URL. Leave blank if this section is a dropdown.', max_length=200)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PageAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('path', models.CharField(max_length=512)),
                ('method', models.CharField(max_length=10)),
                ('status_code', models.IntegerField()),
                ('user_agent', models.TextField(blank=True)),
                ('referrer', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyTrafficSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(unique=True)),
                ('total_requests', models.PositiveIntegerField(default=0)),
                ('total_404s', models.PositiveIntegerField(default=0)),
                ('total_200s', models.PositiveIntegerField(default=0)),
                ('total_other', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NavLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('url', models.CharField(help_text='Internal or external URL (e.g. /dashboard/ or https://...)', max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('external', models.BooleanField(default=False)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='WoSModels.navsection')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified_creator', models.BooleanField(default=False)),
                ('max_world_slots', models.IntegerField(default=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorldSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('world_name', models.SlugField(help_text='Unique name used in URLs. Only letters, numbers, dashes or underscores.', max_length=100, unique=True)),
                ('version', models.CharField(max_length=50)),
                ('dev_name', models.CharField(blank=True, max_length=100)),
                ('zip_file', models.FileField(blank=True, storage=WoSModels.storage.OverwriteStorage(), upload_to=WoSModels.models.user_zip_path)),
                ('self_hosted_url', models.URLField(blank=True, help_text='Optional external link for self-hosted world ZIP')),
                ('max_file_size_mb', models.IntegerField(default=100)),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('last_updated', models.DateField(blank=True, help_text='Optional manual override for update date. Defaults to upload date.', null=True)),
                ('download_slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
